### ISSUE TITLE
Spaces in formid are transformed to underscores

### ISSUE THREAD

**Issue by lognaturel** [enketo/enketo-transformer#100]
This is a problem for encrypted forms: https://github.com/enketo/enketo-express/issues/252

Confirmed with tests (accents are passed through correctly, only spaces fail):
```
    describe( 'puts attributes on root', () => {
        it( 'copies the formId', () => {
            const xform = fs.readFileSync( './test/forms/widgets.xml', 'utf8' );
            const result = transformer.transform( { xform } );

            return expect( result ).to.eventually.have.property( 'form' ).and.to.contain( 'id="widgets"' );
        } );

        it( 'copies the formId with accents', () => {
            const xform = fs.readFileSync( './test/forms/form-id-with-accent.xml', 'utf8' );
            const result = transformer.transform( { xform } );

            return expect( result ).to.eventually.have.property( 'form' ).and.to.contain( 'Éphémère' );
        } );

        it( 'copies the formId with spaces', () => {
            const xform = fs.readFileSync( './test/forms/form-id-with-space.xml', 'utf8' );
            const result = transformer.transform( { xform } );

            return expect( result ).to.eventually.have.property( 'form' ).and.to.contain( 'FormId with spaces' );
        } );
    } );
```

Seems it's from
https://github.com/enketo/enketo-transformer/blob/530125089e5891d3f426742a4c8bbc9a0e5d2858/src/xsl/openrosa2html5form.xsl#L111

I can remove the replace without any tests failing. I can't easily do a blame to find out why that was introduced because the file moved repos. @MartijnR would you happen to remember? The "not smart" comment implies there was a sense it could cause a problem but I don't see why it exists.

**Comment by MartijnR** [comment]
Gee, that must be one of the most helpful code comments I left.... I'll have a look. These XLS sheets used to be in their own repo.

**Comment by MartijnR** [comment]
Couldn't find the commit, but I know why this was done now. An `id` attribute in HTML cannot contain spaces: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id.

So I guess, we'd have to switch to something like `data-form-id`. Probably doesn't touch a lot of code, but we'd have to find the few places it does.

**Comment by lognaturel** [comment]
Ah, interesting, thanks so much for looking into it.

The results from the transformer are cached, right? So every access point would have to try the new attribute and then fall back to id if it doesn’t exist?

**Comment by MartijnR** [comment]
The cached results of the transformer will be discarded with a new version of Enketo Transformer, so when updating enketo-core and enketo-transformer (and enketo-express) simultaneously we should be good without fallback. I believe the local browser database doesn't use the form ID (only Enketo ID and instance ID).

> Browsers treat non-conforming IDs that contain whitespace as if the whitespace is part of the ID.

I hadn't read that second sentence ;). I guess checking if our browsers do this correctly, and keeping `id` if they do, would also be fine. Seems like a pretty minor violation.

**Comment by lognaturel** [comment]
> The cached results of the transformer will be discarded with a new version of Enketo Transformer

Great, that makes sense! In that case I prefer switching to a custom attribute. That way there's no issue with browsers changing how they treat that case over time. If that sounds ok to you, I'll [try to] make it so.

**Comment by MartijnR** [comment]
Great!
