### ISSUE TITLE
Consider depending on a stable release of `express` dependency

### ISSUE THREAD

**Issue by eyelidlessness** [enketo/enketo-transformer#118]
As discussed in #112, we currently depend on an alpha release of `express`, which is probably not ideal. We should determine what (if any) breaking changes this alpha release has introduced, and whether we're depending on those. If not, we should probably depend on the latest stable release (4.x) instead.

**Comment by MartijnR** [comment]
Express is used for the web api which we don't use internally (except for development). I think that's why it was so permissive. However, we don't know how others are using this tools, so makes sense to me to use a fixed non-alpha release.

**Comment by lognaturel** [comment]
A beta just came out yesterday. Central uses 4.16.

**Comment by lognaturel** [comment]
Addressed by https://github.com/enketo/enketo-transformer/commit/6b0e4c3ad30ed2f814ac900fbfa6c2b973822070
