### ISSUE TITLE
Webform always display datalist to render choice question when using search appearance.

### ISSUE THREAD

**Issue by nanzhang01** [enketo/enketo-transformer#128]
- When using the search appearance, the web app always displays the list using the autocomplete experience. This makes the question look like a text question (until you type something) rather than a list.  Although autocomplete will work in many cases,  but enketo-transformer locks authors to that appearance and authors has no chance to change it. 

- If the issue is that we do not want to render many choices in the web browser in the event that the query results in many records, we think we should leave that issue for resolution by the author. 

- If value in image column is filled, author want to show image in choice options with search appearance, author will find it not work. 

From Survey123 perspective, it will be nice if this default behaviour is removed.

**Comment by lognaturel** [comment]
`search` and `autocomplete` are intended to be aliases of each other. What different experience do you expect for `search`?

**Comment by lognaturel** [comment]
I stumbled upon https://github.com/getodk/xforms-spec/issues/124#issuecomment-300327353 looking for something else:

`Survey123 used appearance="autocomplete" and ODK Collect used appearance="search" for the same feature.`
