### ISSUE TITLE
Error resolving dependencies on package install

### ISSUE THREAD

**Issue by JGreenlee** [enketo/enketo-transformer#177]
I have been unable to use `enketo-transformer` due to dependency issues. I first encountered the issue with version 2.1.5, but face the same issue on 2.3 (latest).

I was able to reproduce the issue on both Mac and Windows Node environments. I also tried both Node version 16 and 14.

It seems to be looking for a binary at `https://github.com/MrMYHuang/libxmljs/releases/download/v1.0.4-mt/node-v83-win32-x64.tar.gz`, which is not found, and then it attempts to build the binary itself from the source (which fails because I do not have those C++ libraries)

I thought the issue may have been my project so I tried to install `enketo-transformer` to a new, blank Node project. Same result.

```
$ nvm use 14 && npm i enketo-transformer
Now using node v14.18.1 (npm v6.14.15)
npm WARN deprecated node-pre-gyp@0.9.1: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future

> node1-libxmljsmt-myh@1.0.4 install C:\Users\jax12\Documents\projects\test\node_modules\node1-libxmljsmt-myh
> node-pre-gyp install --fallback-to-build --loglevel http

node-pre-gyp http GET https://github.com/MrMYHuang/libxmljs/releases/download/v1.0.4-mt/node-v83-win32-x64.tar.gz
node-pre-gyp http 404 https://github.com/MrMYHuang/libxmljs/releases/download/v1.0.4-mt/node-v83-win32-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/MrMYHuang/libxmljs/releases/download/v1.0.4-mt/node-v83-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node1-libxmljsmt-myh@1.0.4 and node@14.18.1 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/MrMYHuang/libxmljs/releases/download/v1.0.4-mt/node-v83-win32-x64.tar.gz
gyp ERR! find VS 
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS unknown version "undefined" found at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
...
...
(continued)
```
---

Is this working for other people? Anything I'm doing wrong?

**Comment by lognaturel** [comment]
We all build the binaries locally. Unfortunately I don't think any of us who are commonly around these parts use Windows so you may have to look to Stackoverflow or other resources for the best approach.

**Comment by JGreenlee** [comment]
Ah I see, I didn't realize I needed a C++ toolchain for this, as I thought it would just grab precompiled binaries from somewhere.

Referring to the [node-gyp requirements](https://github.com/nodejs/node-gyp#on-macos) got me what I needed. If you think other people might run into the same problem, I would just direct them there or maybe add this link to the prerequisites in the readme.

I also needed to make sure my environment was using Python 3.10, not Python 3.11 because of [this issue with node-gyp](https://github.com/nodejs/node-gyp/issues/2219).

Thanks for your help! The recent work to support client-side transformation looks great too!

**Comment by lognaturel** [comment]
> I thought it would just grab precompiled binaries from somewhere.

The upstream XSLT and XML libraries we use are largely unmaintained so there's no one currently publishing binaries for them. I've wanted to look into how to at least add the binary I build for myself but haven't had the cycles to look into it. Consider doing that if you want!

I'm glad you were able to figure it out. Do you want to add a quick note to the readme? Since you've just run into the issue I think you're well-positioned to put the note in the most useful place and provide the right level of information.

Also very interested in hearing what you're using Enketo for if you're willing to share. Thanks!
