### ISSUE TITLE
Error importing enketo-transform/web: Module not found: Error: Default condition should be last one

### ISSUE THREAD

**Issue by raphaelmerx** [enketo/enketo-transformer#183]
## Description

Trying to setup a bare bone React app and adding `import { transform } from 'enketo-transformer/web';`, I get error `Module not found: Error: Default condition should be last one`. Happens for both versions 2.3.0 and 3.0.0.

Interestingly I'm getting the same error when running `npm run demo` in this repo's demo. But not when running `npm run dev` as the vite config is patching the resolution for enketo-transformer when in dev mode.

## Reproduction steps
```bash
git clone https://github.com/raphaelmerx/xlsform-playground && cd xlsform-playground
npm i
npm run start
```

## Environment
Ubuntu 22.04, node v16.20.1, npm 6.14.18

## Use case
After reading the ODK summit report, wanted to try setting up a small website where one can edit an XLSForm and see the result on an Enketo form quickly, using browser-side enketo-transformer.

**Comment by lognaturel** [comment]
Thank you for filing and fixing this, @raphaelmerx! I'm surprised the issue managed to go undetected with all the places we use Transformer in. I'd like @eyelidlessness to take a quick look before merging in case he has ideas on how we could have caught it.

> setting up a small website where one can edit an XLSForm and see the result on an Enketo form quickly, using browser-side enketo-transformer.

That sounds great! Do you know about https://getodk.org/xlsform/ (https://github.com/getodk/xlsform-online)? That does use client side transformation (the `/preview` Enketo Express endpoint it uses always does now). We'd consider replacing it with something with a better interface if you have something to propose!

**Comment by raphaelmerx** [comment]
> Do you know about https://getodk.org/xlsform/ (https://github.com/getodk/xlsform-online)? 

I did but had missed that it supported form previews too! 🥲 

I think there might be value in building something that keeps everything in one webpage though, both the xlsform editing and the preview. I have a very early stage prototype at https://github.com/raphaelmerx/xlsform-play:


https://github.com/enketo/enketo-transformer/assets/5139869/36ebabef-35c6-497f-9e49-517835b5a452


However by editing the xlsform in a browser, you lose the spreadsheet environment that one is used to. Anyways, I need to  work further on this before saying with confidence that it's useful. Will keep you posted!
