### ISSUE TITLE
Add node 0.12 support

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-transformer#4]
Nearly there. Libxslt 0.5.1 has the support but it won't install via npm at the moment: https://github.com/albanm/node-libxslt/issues/15

**Comment by alxndrsn** [comment]
Any update on this?  Looks like libxslt `0.5.1` is available in npm: https://www.npmjs.com/package/libxslt

However, I've tried to upgrade locally and get:

```
...
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/user/workspaces/medic/enketo-client-side-transformer/enketo-transformer/node_modules/enketo-transformer/node_modules/libxslt/node_modules/libxmljs
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "../../enketo-transformer"
npm ERR! node v0.12.7
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE

npm ERR! libxmljs@0.14.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxmljs@0.14.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.
```
Any ideas?

**Comment by MartijnR** [comment]
Building works now with the latest node-libxslt. However, I'm seeing an issue actually loading the module. 

Don't have much time this week to get to the bottom of this and file a bug report with node-libxslt, but am hoping to do this (or that somebody else does this before me). 

Progress nonetheless! :)

**Comment by alxndrsn** [comment]
By building, do you mean `npm pack`?  I have no problems running that.
I don't think I understand what's going on well enough to file a bug with `node-libxslt`.  Would the above log be enough for them to work with?

**Comment by MartijnR** [comment]
No, I meant `npm install libxslt`.

I think you may just have to `rm node_modules` update npm's internal node-gyp (see node-libxslt readme), and then `npm install libxslt` should work in both node 0.10 and 0.12.

**Comment by alxndrsn** [comment]
Thanks, I'll look into it.

**Comment by MartijnR** [comment]
Forgot to mention, it doesn't actually build successfully in OS X for me, just in Ubuntu. Probably some build dependency that is not up to date in OS X (one of the ones contained in apt-get's build-essential package) . I just saw in your logs, that you're using OS X as well.

**Comment by MartijnR** [comment]
https://github.com/albanm/node-libxslt/issues/18
