### ISSUE TITLE
Add Central Kurdish (Sorani) to known RTL languages

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-transformer#51]
* [ ] in enketo-transformer
* [ ] in i18next (send PR)

**Comment by jogoool** [comment]
Any update on this!!!

**Comment by MartijnR** [comment]
Not after reporting it solved... If there is a bug please open a new issue and add a simple form to reproduce.

**Comment by jogoool** [comment]
How do you solve it?

**Comment by MartijnR** [comment]
I’m not sure what you mean. It was a bug and as far as I know it is fixed. Are you experiencing a problem?

Try uploading your form in Sorani to http://opendatakit.org/xlsform/ and click Preview in Enketo.

If Sorani is not displayed from right to left, please share your xlsform in this thread. I’ll reopen this as I’m guessing you’re experiencing a problem. (PS, am on holiday so won’t respond in next week).

**Comment by MartijnR** [comment]
re-closed as no bug report received
