### ISSUE TITLE
Fix Node 10 and 12 incompatibility

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-transformer#53]
https://github.com/albanm/node-libxslt/issues/68

* [x] add note
* [ ] update when node-libxslt is fixed

**Comment by ediyacoo** [comment]
Wondering any updates to support Node 10.x?

**Comment by MartijnR** [comment]
Best to track the issue linked above. We don't have the expertise to fix this ourselves unfortunately.

**Comment by ediyacoo** [comment]
Thanks @MartijnR. 

It seems the https://github.com/alexdee2007/node-libxslt has a fix for node 10.x. Would you like to use it for enketo-transformer? or prefer to wait until `node-libxslt` fixes this?

**Comment by MartijnR** [comment]
I think at this point we should probably use the fork.

**Comment by MartijnR** [comment]
@alexdee2007, it looks like a simpler version of node-libxslt has some demand (we, for example, never use stylesheets referenced in other stylesheets). I just wanted to check if you wanted to publish your fork with the libxml dependency (instead of libxml-mt)  on npm. Would become instantly popular :D!

**Comment by alexdee2007** [comment]
Hello @MartijnR, I’ll do it in the near future. 
Unfortunately, I don’t have enough time for now.

**Comment by MartijnR** [comment]
another option (but less nice): http://xmlsoft.org/XSLT/xsltproc.html
