### ISSUE TITLE
media file type csv not working in transform

### ISSUE THREAD

**Issue by awemulya** [enketo/enketo-transformer#55]
Media files  for type media `jr://images/a.jpg` are working but `src="jr://file-csv/amediggs.csv">` in 
`curl -d "xform=<xform>x</xform>&theme=plain&media[a.jpg]=/path/to/a.png&media[amediggs.csv]=/path/to/a.csv" http://localhost:8085/transform`

In the response form data images are relpaced with url of image `/path/to/a.png`
but csv file `src="jr://file-csv/amediggs.csv">` is disappeared.

Have  I missed something.

**Comment by awemulya** [comment]
curl response form 
`
<form autocomplete="off" novalidate="novalidate" class="or clearfix" dir="ltr" id="arTEXxmRXdND8F37aZutdk">
<section class="form-logo"> </section><h3 dir="auto" id="form-title">Amediggs</h3><select id="form-languages" style="display:none;" data-default-lang="default"><option value="default" data-dir="ltr">default</option> </select>
  
  
    <section class="or-group " name="/arTEXxmRXdND8F37aZutdk/group_aa7ot56"><h4><span lang="" class="question-label active">La Entrega</span></h4><label class="question non-select "><span lang="" class="question-label active">Por favor completa los datos para confirmar le Entrega.</span><input type="text" name="/arTEXxmRXdND8F37aZutdk/group_aa7ot56/Por_favor_completa_l_confirmar_le_Entrega" data-type-xml="string" readonly="readonly"/></label><label class="question non-select "><span lang="" class="question-label active">Codigo del Orden de Entrega</span><span class="required">*</span><input type="text" name="/arTEXxmRXdND8F37aZutdk/group_aa7ot56/Codigo" data-required="true()" data-type-xml="string"/><span class="or-required-msg active" lang="" data-i18n="constraint.required">This field is required</span></label>
            </section>
    <section class="or-group or-appearance-field-list " name="/arTEXxmRXdND8F37aZutdk/group_qh5ln36"><h4><span lang="" class="question-label active">Confirmación del Orden</span></h4><label class="question non-select or-appearance-field-list "><span lang="" class="question-label active">Codigo: <span class="or-output" data-value=" /arTEXxmRXdND8F37aZutdk/group_aa7ot56/Codigo "> </span></span><input type="text" name="/arTEXxmRXdND8F37aZutdk/group_qh5ln36/note_Codigo" data-type-xml="string" readonly="readonly"/></label><label class="question non-select "><span lang="" class="question-label active">Unidad Médico Destino: <span class="or-output" data-value=" /arTEXxmRXdND8F37aZutdk/IdNombreUnidad "> </span></span><input type="text" name="/arTEXxmRXdND8F37aZutdk/group_qh5ln36/note_IdNombreUnidad" data-type-xml="string" readonly="readonly"/></label><label class="question non-select "><span lang="" class="question-label active">Lote o Medicamento Adjudicado: <span class="or-output" data-value=" /arTEXxmRXdND8F37aZutdk/CodigoProducto "> </span></span><input type="text" name="/arTEXxmRXdND8F37aZutdk/group_qh5ln36/note_CondigoProducto" data-type-xml="string" readonly="readonly"/></label><label class="question non-select "><span lang="" class="question-label active">Cantidad Requerida: <span class="or-output" data-value=" /arTEXxmRXdND8F37aZutdk/CantidadRequerida "> </span></span><input type="text" name="/arTEXxmRXdND8F37aZutdk/group_qh5ln36/note_CantidadRequerida" data-type-xml="string" readonly="readonly"/></label><fieldset class="question simple-select trigger "><fieldset><legend><span lang="" class="question-label active">Los datos del orden son correctos.</span><span class="required">*</span>
                    </legend><div class="option-wrapper"><label><input value="OK" type="radio" name="/arTEXxmRXdND8F37aZutdk/group_qh5ln36/confirmacion_orden" data-name="/arTEXxmRXdND8F37aZutdk/group_qh5ln36/confirmacion_orden" data-required="true()" data-type-xml="string"/><span class="option-label active" lang="">OK</span></label></div></fieldset><span class="or-required-msg active" lang="" data-i18n="constraint.required">This field is required</span></fieldset>
            </section>
    <fieldset class="question simple-select "><fieldset><legend><span lang="default" class="question-label active" data-itext-id="/arTEXxmRXdND8F37aZutdk/Is_this_a_man:label">Is this a man??</span><img lang="default" class="active" src="https://naxafieldsight.s3.amazonaws.com/santoshk/formid-media/man_cC9XEE9.jpg" data-itext-id="/arTEXxmRXdND8F37aZutdk/Is_this_a_man:label" alt="image"/>
                    </legend><div class="option-wrapper"><label class=""><input type="radio" name="/arTEXxmRXdND8F37aZutdk/Is_this_a_man" data-name="/arTEXxmRXdND8F37aZutdk/Is_this_a_man" value="yes" data-type-xml="select1"/><span lang="" class="option-label active">Yes</span></label><label class=""><input type="radio" name="/arTEXxmRXdND8F37aZutdk/Is_this_a_man" data-name="/arTEXxmRXdND8F37aZutdk/Is_this_a_man" value="no" data-type-xml="select1"/><span lang="" class="option-label active">No</span></label></div></fieldset></fieldset>
    <fieldset class="question simple-select "><fieldset><legend><span lang="default" class="question-label active" data-itext-id="/arTEXxmRXdND8F37aZutdk/Am_I_a_joke_to_you:label">Am I a joke to you????</span><img lang="default" class="active" src="https://naxafieldsight.s3.amazonaws.com/santoshk/formid-media/joke_pm0hpA2.jpg" data-itext-id="/arTEXxmRXdND8F37aZutdk/Am_I_a_joke_to_you:label" alt="image"/><span class="required">*</span>
                    </legend><div class="option-wrapper"><label class=""><input type="radio" name="/arTEXxmRXdND8F37aZutdk/Am_I_a_joke_to_you" data-name="/arTEXxmRXdND8F37aZutdk/Am_I_a_joke_to_you" value="yes_yess" data-required="true()" data-type-xml="select1"/><span lang="" class="option-label active">Yes YESS!!</span></label></div></fieldset><span class="or-required-msg active" lang="" data-i18n="constraint.required">This field is required</span></fieldset>
  
<fieldset id="or-preload-items" style="display:none;"><label class="calculation non-select "><input type="hidden" name="/arTEXxmRXdND8F37aZutdk/start" data-preload="timestamp" data-preload-params="start" data-type-xml="dateTime"/></label><label class="calculation non-select "><input type="hidden" name="/arTEXxmRXdND8F37aZutdk/end" data-preload="timestamp" data-preload-params="end" data-type-xml="dateTime"/></label></fieldset><fieldset id="or-calculated-items" style="display:none;"><label class="calculation non-select "><input type="hidden" name="/arTEXxmRXdND8F37aZutdk/IdNombreUnidad" data-calculate="pulldata('amediggs','IDNombreUnidad','Codigo', /arTEXxmRXdND8F37aZutdk/group_aa7ot56/Codigo )" data-type-xml="string"/></label><label class="calculation non-select "><input type="hidden" name="/arTEXxmRXdND8F37aZutdk/CodigoProducto" data-calculate="pulldata('amediggs','CodigoProducto','Codigo', /arTEXxmRXdND8F37aZutdk/group_aa7ot56/Codigo )" data-type-xml="string"/></label><label class="calculation non-select "><input type="hidden" name="/arTEXxmRXdND8F37aZutdk/CantidadRequerida" data-calculate="pulldata('amediggs','CantidadRequerida','Codigo', /arTEXxmRXdND8F37aZutdk/group_aa7ot56/Codigo )" data-type-xml="string"/></label><label class="calculation non-select "><input type="hidden" name="/arTEXxmRXdND8F37aZutdk/__version__" data-calculate="'vMHTitro56KYwhbpheQRkf'" data-type-xml="string"/></label><label class="calculation non-select "><input type="hidden" name="/arTEXxmRXdND8F37aZutdk/_version_" data-calculate="'vzJfZMfiqZan5DRzEUtcCJ'" data-type-xml="string"/></label><label class="calculation non-select "><input type="hidden" name="/arTEXxmRXdND8F37aZutdk/meta/instanceID" data-calculate="concat('uuid:', uuid())" data-type-xml="string"/></label><label class="calculation non-select "><input type="hidden" name="/arTEXxmRXdND8F37aZutdk/formhub/uuid" data-calculate="'1de44259675d452092995d639aa49ef8'" data-type-xml="string"/></label></fieldset></form>`

**Comment by awemulya** [comment]
Xform XML
`
<?xml version="1.0" encoding="utf-8"?>
<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:jr="http://openrosa.org/javarosa" xmlns:odk="http://www.opendatakit.org/xforms" xmlns:orx="http://openrosa.org/xforms" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <h:head>
    <h:title>Amediggs</h:title>
    <model>
      <itext>
        <translation default="true()" lang="default">
          <text id="/arTEXxmRXdND8F37aZutdk/Am_I_a_joke_to_you:label">
            <value form="image">jr://images/joke.jpg</value>
            <value>Am I a joke to you????</value>
          </text>
          <text id="/arTEXxmRXdND8F37aZutdk/Is_this_a_man:label">
            <value form="image">jr://images/man.jpg</value>
            <value>Is this a man??</value>
          </text>
        </translation>
      </itext>
      <instance>
        <arTEXxmRXdND8F37aZutdk id="arTEXxmRXdND8F37aZutdk" version="vzJfZMfiqZan5DRzEUtcCJ">
          <formhub>
            <uuid/>
          </formhub>
          <start/>
          <end/>
          <group_aa7ot56>
            <Por_favor_completa_l_confirmar_le_Entrega/>
            <Codigo>ITB</Codigo>
          </group_aa7ot56>
          <IdNombreUnidad/>
          <CodigoProducto/>
          <CantidadRequerida/>
          <group_qh5ln36>
            <note_Codigo/>
            <note_IdNombreUnidad/>
            <note_CondigoProducto/>
            <note_CantidadRequerida/>
            <confirmacion_orden/>
          </group_qh5ln36>
          <Is_this_a_man/>
          <Am_I_a_joke_to_you/>
          <__version__/>
          <_version_/>
          <meta>
            <instanceID/>
          </meta>
        </arTEXxmRXdND8F37aZutdk>
      </instance>
      <instance id="amediggs" src="jr://file-csv/amediggs.csv">
        <root>
          <item>
            <name>_</name>
            <label>_</label>
          </item>
        </root>
      </instance>
      <bind jr:preload="timestamp" jr:preloadParams="start" nodeset="/arTEXxmRXdND8F37aZutdk/start" type="dateTime"/>
      <bind jr:preload="timestamp" jr:preloadParams="end" nodeset="/arTEXxmRXdND8F37aZutdk/end" type="dateTime"/>
      <bind nodeset="/arTEXxmRXdND8F37aZutdk/group_aa7ot56/Por_favor_completa_l_confirmar_le_Entrega" readonly="true()" required="false()" type="string"/>
      <bind nodeset="/arTEXxmRXdND8F37aZutdk/group_aa7ot56/Codigo" required="true()" type="string"/>
      <bind calculate="pulldata('amediggs','IDNombreUnidad','Codigo', /arTEXxmRXdND8F37aZutdk/group_aa7ot56/Codigo )" nodeset="/arTEXxmRXdND8F37aZutdk/IdNombreUnidad" required="true()" type="string"/>
      <bind calculate="pulldata('amediggs','CodigoProducto','Codigo', /arTEXxmRXdND8F37aZutdk/group_aa7ot56/Codigo )" nodeset="/arTEXxmRXdND8F37aZutdk/CodigoProducto" required="true()" type="string"/>
      <bind calculate="pulldata('amediggs','CantidadRequerida','Codigo', /arTEXxmRXdND8F37aZutdk/group_aa7ot56/Codigo )" nodeset="/arTEXxmRXdND8F37aZutdk/CantidadRequerida" required="true()" type="string"/>
      <bind nodeset="/arTEXxmRXdND8F37aZutdk/group_qh5ln36/note_Codigo" readonly="true()" required="false()" type="string"/>
      <bind nodeset="/arTEXxmRXdND8F37aZutdk/group_qh5ln36/note_IdNombreUnidad" readonly="true()" required="false()" type="string"/>
      <bind nodeset="/arTEXxmRXdND8F37aZutdk/group_qh5ln36/note_CondigoProducto" readonly="true()" required="false()" type="string"/>
      <bind nodeset="/arTEXxmRXdND8F37aZutdk/group_qh5ln36/note_CantidadRequerida" readonly="true()" required="false()" type="string"/>
      <bind nodeset="/arTEXxmRXdND8F37aZutdk/group_qh5ln36/confirmacion_orden" required="true()" type="string"/>
      <bind nodeset="/arTEXxmRXdND8F37aZutdk/Is_this_a_man" required="false()" type="select1"/>
      <bind nodeset="/arTEXxmRXdND8F37aZutdk/Am_I_a_joke_to_you" required="true()" type="select1"/>
      <bind calculate="'vMHTitro56KYwhbpheQRkf'" nodeset="/arTEXxmRXdND8F37aZutdk/__version__" type="string"/>
      <bind calculate="'vzJfZMfiqZan5DRzEUtcCJ'" nodeset="/arTEXxmRXdND8F37aZutdk/_version_" type="string"/>
      <bind calculate="concat('uuid:', uuid())" nodeset="/arTEXxmRXdND8F37aZutdk/meta/instanceID" readonly="true()" type="string"/>
      <bind calculate="'1de44259675d452092995d639aa49ef8'" nodeset="/arTEXxmRXdND8F37aZutdk/formhub/uuid" type="string"/>
    </model>
  </h:head>
  <h:body>
    <group ref="/arTEXxmRXdND8F37aZutdk/group_aa7ot56">
      <label>La Entrega</label>
      <input ref="/arTEXxmRXdND8F37aZutdk/group_aa7ot56/Por_favor_completa_l_confirmar_le_Entrega">
        <label>Por favor completa los datos para confirmar le Entrega.</label>
      </input>
      <input ref="/arTEXxmRXdND8F37aZutdk/group_aa7ot56/Codigo">
        <label>Codigo del Orden de Entrega</label>
      </input>
    </group>
    <group appearance="field-list" ref="/arTEXxmRXdND8F37aZutdk/group_qh5ln36">
      <label>Confirmación del Orden</label>
      <input appearance="field-list" ref="/arTEXxmRXdND8F37aZutdk/group_qh5ln36/note_Codigo">
        <label>Codigo: <output value=" /arTEXxmRXdND8F37aZutdk/group_aa7ot56/Codigo "/></label></input>
      <input ref="/arTEXxmRXdND8F37aZutdk/group_qh5ln36/note_IdNombreUnidad">
        <label>Unidad Médico Destino: <output value=" /arTEXxmRXdND8F37aZutdk/IdNombreUnidad "/></label></input>
      <input ref="/arTEXxmRXdND8F37aZutdk/group_qh5ln36/note_CondigoProducto">
        <label>Lote o Medicamento Adjudicado: <output value=" /arTEXxmRXdND8F37aZutdk/CodigoProducto "/></label></input>
      <input ref="/arTEXxmRXdND8F37aZutdk/group_qh5ln36/note_CantidadRequerida">
        <label>Cantidad Requerida: <output value=" /arTEXxmRXdND8F37aZutdk/CantidadRequerida "/></label></input>
      <trigger ref="/arTEXxmRXdND8F37aZutdk/group_qh5ln36/confirmacion_orden">
        <label>Los datos del orden son correctos.</label>
      </trigger>
    </group>
    <select1 ref="/arTEXxmRXdND8F37aZutdk/Is_this_a_man">
      <label ref="jr:itext('/arTEXxmRXdND8F37aZutdk/Is_this_a_man:label')"/>
      <item>
        <label>Yes</label>
        <value>yes</value>
      </item>
      <item>
        <label>No</label>
        <value>no</value>
      </item>
    </select1>
    <select1 ref="/arTEXxmRXdND8F37aZutdk/Am_I_a_joke_to_you">
      <label ref="jr:itext('/arTEXxmRXdND8F37aZutdk/Am_I_a_joke_to_you:label')"/>
      <item>
        <label>Yes YESS!!</label>
        <value>yes_yess</value>
      </item>
    </select1>
  </h:body>
</h:html>

`

**Comment by MartijnR** [comment]
Hi @awemulya,

The `<instance>` is not part of the `form` response. It's part of the `model` response. Does that answer your question?

**Comment by awemulya** [comment]
In model response there is csv file url, 
`
<model><instance>
        <arTEXxmRXdND8F37aZutdk xmlns:jr="http://openrosa.org/javarosa" xmlns:odk="http://www.opendatakit.org/xforms" xmlns:orx="http://openrosa.org/xforms" id="arTEXxmRXdND8F37aZutdk" version="vzJfZMfiqZan5DRzEUtcCJ">
          <formhub>
            <uuid/>
          </formhub>
          <start/>
          <end/>
          <group_aa7ot56>
            <Por_favor_completa_l_confirmar_le_Entrega/>
            <Codigo>ITB</Codigo>
          </group_aa7ot56>
          <IdNombreUnidad/>
          <CodigoProducto/>
          <CantidadRequerida/>
          <group_qh5ln36>
            <note_Codigo/>
            <note_IdNombreUnidad/>
            <note_CondigoProducto/>
            <note_CantidadRequerida/>
            <confirmacion_orden/>
          </group_qh5ln36>
          <Is_this_a_man/>
          <Am_I_a_joke_to_you/>
          <__version__/>
          <_version_/>
          <meta>
            <instanceID/>
          </meta>
        </arTEXxmRXdND8F37aZutdk>
      </instance><instance id="amediggs" src="https://s3.amazonaws.com/santoshk/formid-media/amediggs_i7YPOlp.csv">
        <root xmlns:jr="http://openrosa.org/javarosa" xmlns:odk="http://www.opendatakit.org/xforms" xmlns:orx="http://openrosa.org/xforms">
          <item>
            <name>_</name>
            <label>_</label>
          </item>
        </root>
      </instance></model>
`

**Comment by awemulya** [comment]
But in Network console of browser only media types images are downloaded.
Csv file is not been downloaded.

![Screenshot from 2019-06-27 10-25-07](https://user-images.githubusercontent.com/5351212/60235171-91e28980-98c6-11e9-9303-27f45ed07022.png)

**Comment by awemulya** [comment]
Every thing is working fine except csv file calculations. I am wondering why the csv file has not been tried to download. here is the public link of page please have a glance
https://fieldsight.naxa.com.np/forms/new-submission/1268833/81658/
username: aweamulya@gmail.com
password: aaaaaa

**Comment by MartijnR** [comment]
Ah I understand. I think you're using Enketo Core right? Downloading of external data takes place outside of Enketo Core. So you should pass that data when instantiating the Form. See the `external` property: https://enketo.github.io/enketo-core/tutorial-00-getting-started.html

**Comment by MartijnR** [comment]
FieldSight looks cool!

**Comment by awemulya** [comment]
Thank You @MartijnR for Your Guidance. Now it works as expected.
