### ISSUE TITLE
libxslt blocks upgrade to npm >6 and node >12

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-transformer#98]
As described in https://github.com/enketo/enketo-express/issues/240

**Comment by lognaturel** [comment]
This also blocks using node versions greater than 12.

`libxslt` is open to new maintainers: https://github.com/albanm/node-libxslt/issues/68#issuecomment-461075364

I think we should also evaluate level of effort for doing transformations without XSLT.

**Comment by MartijnR** [comment]
> @MartijnR have you had any conversations beyond that with the maintainer or other users of the library?

Only [here](https://github.com/enketo/enketo-transformer/issues/53#issuecomment-553640018) as far as I can recall.

**Comment by lognaturel** [comment]
Some next steps:
- Look for drop-in replacements that are maintained across node version updates
- Explore getting `node-libxslt` to support node 16 (mostly C++ changes; can someone with limited C++ experience do this safely?)
- Evaluate level of effort for doing transformations without XSLT

I started a thread at https://github.com/albanm/node-libxslt/issues/83 about maintenance. The original author and sole maintainer is responsive and willing to review PRs but hasn't used the lib in a long time so it doesn't make sense for him to invest time in. I'm hoping other users with more C++ experience chime in but I don't know how likely it is.

**Comment by lognaturel** [comment]
I now have `node-libxslt` supporting node 16 -- https://github.com/albanm/node-libxslt/pull/84. Right now only 14 and 16 are supported. Is there a strong need to keep support for node 12? I'm going to give it a try but not sure it's worth much investment.

**Comment by lognaturel** [comment]
Thanks to @albanm's speedy review, [node-libxslt 0.10.0](https://www.npmjs.com/package/libxslt) is now available! 🎉

Currently it would allow us to bump node to 16 but npm would have to stay at 6 because of what looks like a bug in 7. I've filed at https://github.com/npm/cli/issues/3556 and I think we can give that a little bit to settle as we decide what node version to pin to and explore the implications for the various repos.
